### ISSUE TITLE
Excepção no jar criado através do bootjar

### ISSUE THREAD

**Issue by goncalo42220** [isel-leic-daw/1718v-public#4]
![capturar](https://user-images.githubusercontent.com/26144866/40845484-bdb38b78-65ae-11e8-896b-06a3d8d0c32e.PNG)

Esta excepção é lançada quando executamos o jar a nivel local ou na cloud.

**Comment by pmhsfelix** [comment]
Por favor:
* Verifiquem se o ficheiro está dentro do JAR criado.
* Verifiquem qual a razão para a inclusão dessa dependência (`./gradlew dependencies`).

**Comment by tiagobluiz** [comment]
O problema com o Jetty foi resolvido e a instância já inicia o Spring, contudo, por algum problema de configuração, desta vez do Spring, dá problema nos portos.

<img width="1096" alt="captura de ecra 2018-06-02 as 14 32 51" src="https://user-images.githubusercontent.com/26139260/40876814-068828e0-6672-11e8-9c04-1d281d4e22dc.png">

**Comment by pmhsfelix** [comment]
É natural que na máquina local já exista outro processo a ocupar o porto 80. Em adição, em CentOS o porto 80 é restrito pelo que devem fazer listen num porto não restrito (e.g. 8080). Como os nós vão estar por detrás do LB não existe problema em fazer listen num porto distinto do 80.

**Comment by tiagobluiz** [comment]
Problema resolvido. Estava a seguir as instruções que o Engenheiro colocou no github e  não me lembrei das restrições aplicadas ao porto referido. Obrigado

**Comment by pmhsfelix** [comment]
Ok. Vou fechar o issue. Reabrir se necessário.
